### ISSUE TITLE
PSX/PS2 PCB has incorrectly numbered vias for L connector

### ISSUE THREAD

**Issue by amaiorano** [pmgducati/Blue-Retro-AIO-Units#67] opened 2023-04-30 02:48 UTC
It looks like the numbering for the L connector vias on the PSX/PS2 PCB is flipped horizontally:

![image](https://user-images.githubusercontent.com/6893883/235333098-49fa3261-17b6-42f3-9932-6437e241ea4d.png)

I was following the traces to make sure I connected my wires right, and was confused that the pad numbers didn't match up with the DB25 pin numbers as per darthcloud's schematic.

**Comment by pmgducati** [comment] 2023-05-03 19:31
The pin numbers are different, I swapped the male and female DB25 connectors so that the female version is on all the system adapters,  That way there is only male connector that could get bent pins and have to be repaired.  With the swap, the pin numbers are reversed on all the PCBs.  The traces all go to the correct pins on the main board and has been tested and verified to work as intended. 

Closing this comment.

**Closed by pmgducati** 2023-05-03 19:31 UTC

**Comment by amaiorano** [comment] 2023-05-03 19:43
> The pin numbers are different, I swapped the male and female DB25 connectors so that the female version is on all the system adapters, That way there is only male connector that could get bent pins and have to be repaired. With the swap, the pin numbers are reversed on all the PCBs. The traces all go to the correct pins on the main board and has been tested and verified to work as intended.

Ah, I see, that makes sense. It's a bit unfortunate because the numbering of the pads on the silkscreen match up with what's in the official schematics, but not the DB25 pin numbers. Anyway, it does indeed work as expected. Thanks.
